BEGIN TRANSACTION;

ALTER TABLE tcp ADD COLUMN dx REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dy REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dz REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN drx REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dry REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN drz REAL NOT NULL DEFAULT 0;

ALTER TABLE joint ADD COLUMN dx REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dy REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dz REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN drx REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dry REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN drz REAL NOT NULL DEFAULT 0;

COMMIT;
