BEGIN TRANSACTION;

ALTER TABLE tcp ADD COLUMN dx REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dy REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dz REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN drx REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN dry REAL NOT NULL DEFAULT 0;
ALTER TABLE tcp ADD COLUMN drz REAL NOT NULL DEFAULT 0;

ALTER TABLE joint ADD COLUMN dj1 REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dj2 REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dj3 REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dj4 REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dj5 REAL NOT NULL DEFAULT 0;
ALTER TABLE joint ADD COLUMN dj6 REAL NOT NULL DEFAULT 0;

COMMIT;
